Append required FITS keywords in ds9_region header
This fixes the error below when creating a ds9 region
~/.local/lib64/python3.6/site-packages/astropy/io/fits/header.py in _cardindex(self, key)
   1652
   1653         if not indices:
-> 1654             raise KeyError("Keyword {!r} not found.".format(keyword))
   1655
   1656         try:
KeyError: "Keyword 'NAXIS1' not found."