Fixed an indexing issue with numpy. Previously this would throw
TypeError: only integer scalar arrays can be converted to a scalar index

See the following StackOverflow:
https://stackoverflow.com/questions/42128830/typeerror-only-integer-scalar-arrays-can-be-converted-to-a-scalar-index